---
title: "MA132 Spring Enrollment Prediction"
author: "Coach Skufca"
date: "2022-10-05"
output: html_notebook
---

Class play with MA132 data.

## Load Packages

```{r}

library(tidyverse)
library(here)
library(janitor)

```

## Load  data

```{r}
myfile=here("data_raw","CU_ACAD_DEPT_WHEN_OFF_ENRL_22740.csv")
df1=read_csv(myfile,skip=1) %>% clean_names()%>%
  filter(component=="LEC") %>%
  filter(catalog %in% c(131,132)) %>%
  select(catalog,section,term,term2,title,tot_enrl)%>%
  mutate(ay=round((term-4000)/10))
  
```

### create and store analysis dataframes

```{r}
file1=here("data","ma132enr_df1")
write_csv(df1,file1)
```

Dataframe 2 will rearrange the data as needed.

```{r}
df2 = df1 %>% 
  separate(term2,c("semester","year"),sep=" ",remove=FALSE) %>%
  filter(semester != "Summer") %>% 
  group_by(ay,term,semester,catalog) %>% summarise(tot_enrl=sum(tot_enrl)) %>%
  ungroup()
```


## Visualize

```{r}
df2 %>% filter(catalog==132,semester=="Spring") %>%
  ggplot(aes(ay,tot_enrl)) +geom_point()
```

### Widen the data


```{r}
df2w = df2 %>% pivot_wider(id_cols=ay,names_from = c(catalog,semester), values_from = tot_enrl)
  
  
  
 df2w %>% filter(`132_Spring`>0) %>%   ggplot(aes(`131_Fall`,`132_Spring`)) +geom_point()
```

```{r}
df2c=df1 %>% distinct() %>%  
  separate(term2,c("semester","year"),sep=" ",remove=FALSE) %>%
  filter(semester != "Summer") %>% 
  group_by(ay,term,semester,catalog) %>% summarise(tot_enrl=sum(tot_enrl)) %>%
  ungroup()

df2wc = df2c %>% pivot_wider(id_cols=ay,names_from = c(catalog,semester), values_from = tot_enrl) 
  
  
  
 df2wc %>% filter(`132_Spring`>0) %>%   ggplot(aes(`131_Fall`,`132_Spring`)) +geom_point()
```
### Modeling

```{r}
dfa=df2wc %>% clean_names()%>% slice(1:7)


mdl1=lm(x132_spring~x131_fall,data=dfa)
summary(mdl1)
```

```{r}



mdl2=lm(x132_spring~x131_fall+x132_fall,data=dfa)
summary(mdl2)
```

```{r}
mdl3=lm(x132_spring~x131_fall+x132_fall+0,data=dfa)
summary(mdl3)
```

```{r}
plot(mdl1)
```

```{r}
plot(mdl3)
```

